FROM gitlab-registry.cern.ch/allpix-squared/allpix-squared/allpix-squared-base:latest
MAINTAINER Simon Spannagel <simon.spannagel@cern.ch>

ENV GEANT4_VERSION 10.03.p03
ENV ROOT6_VERSION 6.10.08

# Add layer for Geant4
ENV GEANT4DIR="/opt/geant4"
ENV PATH="$GEANT4DIR/bin:$PATH"
ENV LD_LIBRARY_PATH="$GEANT4DIR/lib:$LD_LIBRARY_PATH"
ENV G4NEUTRONHPDATA="$GEANT4DIR/share/Geant4-10.3.3/data/G4NDL4.5"
ENV G4LEDATA="$GEANT4DIR/share/Geant4-10.3.3/data/G4EMLOW6.50"
ENV G4LEVELGAMMADATA="$GEANT4DIR/share/Geant4-10.3.3/data/PhotonEvaporation4.3.2"
ENV G4RADIOACTIVEDATA="$GEANT4DIR/share/Geant4-10.3.3/data/RadioactiveDecay5.1.1"
ENV G4NEUTRONXSDATA="$GEANT4DIR/share/Geant4-10.3.3/data/G4NEUTRONXS1.4"
ENV G4PIIDATA="$GEANT4DIR/share/Geant4-10.3.3/data/G4PII1.3"
ENV G4REALSURFACEDATA="$GEANT4DIR/share/Geant4-10.3.3/data/RealSurface1.0"
ENV G4SAIDXSDATA="$GEANT4DIR/share/Geant4-10.3.3/data/G4SAIDDATA1.1"
ENV G4ABLADATA="$GEANT4DIR/share/Geant4-10.3.3/data/G4ABLA3.0"
ENV G4ENSDFSTATEDATA="$GEANT4DIR/share/Geant4-10.3.3/data/G4ENSDFSTATE2.1"

RUN source scl_source enable devtoolset-7 && \
    mkdir -p ${GEANT4DIR}/{src,build} && \
    curl -o ${GEANT4DIR}/geant4.${GEANT4_VERSION}.tar.gz \
            http://geant4-data.web.cern.ch/geant4-data/releases/source/geant4.${GEANT4_VERSION}.tar.gz && \
    tar zxf ${GEANT4DIR}/geant4.${GEANT4_VERSION}.tar.gz -C ${GEANT4DIR}/src && \
    rm -f ${GEANT4DIR}/geant4.${GEANT4_VERSION}.tar.gz && \
    cd ${GEANT4DIR}/build && \
    cmake3 -DGEANT4_INSTALL_DATA=ON \
          -DGEANT4_USE_GDML=ON \
          -DGEANT4_USE_QT=ON \
          -DGEANT4_USE_XM=ON \
          -DGEANT4_USE_OPENGL_X11=ON \
          -DGEANT4_USE_SYSTEM_CLHEP=OFF \
          -DCMAKE_INSTALL_PREFIX=../ \
          ../src/geant4.${GEANT4_VERSION} && \
    make -j`grep -c processor /proc/cpuinfo` && \
    make install && \
    rm -rf ${GEANT4DIR}/{src,build}

# Add layer for ROOT6
ENV ROOTSYS="/opt/root6"
ENV PATH="$ROOTSYS/bin:$PATH"
ENV LD_LIBRARY_PATH="$ROOTSYS/lib:$LD_LIBRARY_PATH"
ENV LIBPATH="$ROOTSYS/lib:$LIBPATH"
ENV PYTHONPATH="$ROOTSYS/lib:$PYTHONPATH"
ENV CMAKE_PREFIX_PATH="$ROOTSYS:$CMAKE_PREFIX_PATH"

RUN source scl_source enable devtoolset-7 && \
    mkdir -p ${ROOTSYS}/{src,build} && \
    curl -o ${ROOTSYS}/root.${ROOT6_VERSION}.tar.gz \
            https://root.cern.ch/download/root_v${ROOT6_VERSION}.source.tar.gz && \
    tar zxf ${ROOTSYS}/root.${ROOT6_VERSION}.tar.gz -C ${ROOTSYS}/src && \
    rm -f ${ROOTSYS}/root.${ROOT6_VERSION}.tar.gz && \
    cd ${ROOTSYS}/build && \
    cmake3 -Dcxx11=ON \
           -Dgdml=ON \
           -Dgenvector=ON \
           -Dmathmore=ON \
           -Dminuit2=ON \
           -Dthread=ON \
           -Dx11=OFF \
           -Dopengl=OFF \
           -DCMAKE_INSTALL_PREFIX=../ \
           ../src/root-${ROOT6_VERSION} && \
    make -j`grep -c processor /proc/cpuinfo` && \
    make install && \
    rm -rf ${ROOTSYS}/{src,build}
